schema_version = "1.0.0"

id = "openbrush_blender_connector"
version = "0.1.0"
name = "Open Brush Blender Connector"
tagline = "Connects Open Brush and Blender APIs via HTTP"
maintainer = "Icosa Foundation"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
website = "https://docs.openbrush.app/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Import-Export", "System"]

blender_version_min = "5.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
    "SPDX:MIT",
]
 # Optional: required by some licenses.
 copyright = [
   "2025 Icosa Foundation",
   "2023 Aarya Gadekar",
 ]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.

[permissions]
network = "We need to send and recieve API requests over HTTP"
files = "Loading, saving and caching of 3d files"
# clipboard = "Copy and paste bone transforms"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]